name: Pubish extension on release

on:
  release:
    types: [published]

jobs:
  lint:
    name: Check for any lint errors
    runs-on: ubuntu-latest
    steps:
      - name: Checking out source code
        uses: actions/checkout@master

      - name: Setting up nodejs version 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Starting lint check
        run: |
          npm install
          npm run lint

  # Need to figure out how to run tests in headless environment
  # test:
  #   name: Verify that tests succeed
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checking out source code
  #       uses: actions/checkout@master

  #     - name: Setting up nodejs version 10
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '10.x'
  #     - name: Starting tests
  #       run: |
  #         npm install
  #         npm test

  publish:
    name: Publish on marketplace
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checking out source code
        uses: actions/checkout@master

      - name: Setting up nodejs version 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Publish to marketplace
        if: github.ref == 'master'
        run: |
          npm i -g vsce
          npm install
          vsce publish -p ${{ secrets.VSCE_TOKEN }}
